{% set name = "viser" %}
{% set version = "0.2.23" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/viser-{{ version }}.tar.gz
  sha256: 07610453da9f01c37eebb03f9611d3a3b18b20e302ca6a00fac36b8fa9bdad57

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - viser-build-client = viser._client_autobuild:build_client_entrypoint

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
  run:
    - python >={{ python_min }}
    - websockets >=13.1
    - numpy >=1.0.0
    - msgspec >=0.18.6
    - imageio >=2.0.0
    - scikit-image >=0.18.0
    - scipy >=1.7.3
    - tqdm >=4.0.0
    - tyro >=0.2.0
    - rich >=13.3.3
    - trimesh >=3.21.7
    - nodeenv >=1.8.0
    - psutil >=5.9.5
    - yourdfpy >=0.0.53
    - plyfile >=1.0.2

test:
  imports:
    - viser
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/nerfstudio-project/viser
  summary: Web-based 3D visualization + Python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
